inertial_frame_id: world
waypoints:
  -
    point: [0, 0, -20]
    max_forward_speed: 2.5
    heading: 0
    use_fixed_heading: False
  -
    point: [50, 0, -20]
    max_forward_speed: 2.5
    heading: 0
    use_fixed_heading: False
  -
    point: [50, 0, 0]
    max_forward_speed: 2.5
    heading: 0
    use_fixed_heading: False
  -
    point: [0, 0, 0]
    max_forward_speed: 2.5
    heading: 0
    use_fixed_heading: False
  